### ISSUE TITLE
7.4.1版本点击播放就闪退

### ISSUE THREAD

**Issue by zhumj** [Jzvd/JiaoZiVideoPlayer#175]
**什么jzvd版本
v7.4.1
**什么播放器内核
默认
**相关log是什么
无WIFI情况：
Process: com.xxx.xxx, PID: 31773
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at cn.jzvd.JzvdStd.showWifiDialog(JzvdStd.java:485)
        at cn.jzvd.Jzvd.clickStart(Jzvd.java:364)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:336)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:326)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
    
连接了WIFI的情况：
Process: com.xxx.xxx, PID: 16214
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at cn.jzvd.JZMediaSystem.prepare(JZMediaSystem.java:34)
        at cn.jzvd.JZMediaSystem.onSurfaceTextureAvailable(JZMediaSystem.java:182)
        at android.view.TextureView.getTextureLayer(TextureView.java:413)
        at android.view.TextureView.draw(TextureView.java:358)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.draw(View.java:21597)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.draw(View.java:21597)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.draw(View.java:21597)
        at android.view.View.updateDisplayListIfDirty(View.java:20471)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4174)
        at android.view.View.updateDisplayListIfDirty(View.java:20462)
        at android.view.View.draw(View.java:21326)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4413)

**demo是否有这个问题
不知道这个问题是什么意思

**自己做了哪些修改
无
**如何操作复现
直接点击播放
**什么安卓版本，什么机型
OnePlus 5  Android 10
**截图或者视频说明情况
闪退

**Comment by zhumj** [comment]
问题找出来了，需要在build.gradle(:app)中的加入以下代码：
`compileOptions{
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}`
