### ISSUE TITLE
 java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.JZMediaInterface.getDuration()' 

### ISSUE THREAD

**Issue by SanYueSI** [Jzvd/JiaoZiVideoPlayer#306]
java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.JZMediaInterface.getDuration()' on a null object reference
        at cn.jzvd.Jzvd.getDuration(Jzvd.java:905)
        at cn.jzvd.Jzvd$ProgressTimerTask.lambda$run$0$Jzvd$ProgressTimerTask(Jzvd.java:1120)
        at cn.jzvd.-$$Lambda$Jzvd$ProgressTimerTask$1zOf0X1AJWTfG4NszoBAvJB_9MM.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

cn.jzvd:jiaozivideoplayer:7.4.2 版本

这个错误根本原因是啥

**Comment by Liberations** [comment]
JZMediaInterface 为空
