### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference

### ISSUE THREAD

**Issue by xxxifan** [Jzvd/JiaoZiVideoPlayer#327]
**什么jzvd版本
7.6.0
**什么播放器内核
exoplayer
**相关log是什么
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5509)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:5472)
       at cn.jzvd.Jzvd.gotoNormalCompletion(Jzvd.java:690)
       at cn.jzvd.Jzvd.onCompletion(Jzvd.java:680)
       at cn.jzvd.JzvdStd.onCompletion(JzvdStd.java:927)
       at com.xxx.ui.JZMediaExo.lambda$onPlayerStateChanged$3(JZMediaExo.java:251)
       at com.xxx.ui.JZMediaExo.lambda$onPlayerStateChanged$3$JZMediaExo(JZMediaExo.java:1)
       at com.xxx.ui.-$$Lambda$JZMediaExo$I61nNcn3880rphoXomUDgsUJfqc.run(-.java:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:264)
       at android.app.ActivityThread.main(ActivityThread.java:7593)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```
**demo是否有这个问题

**自己做了哪些修改
无
**如何操作复现

**什么安卓版本，什么机型
很广泛，从andorid8 - 10都有发现，很多机型。
**截图或者视频说明情况

根据堆栈信息，问题出现于全屏状态，主动退出全屏或者播放完毕自动退出全屏（根据代码gotoNormalCompletion应该是播放完成退出全屏，主动退出全屏的错误堆栈在这：）
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5541)
       at android.view.ViewGroup.removeViewAt(ViewGroup.java:5504)
       at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1003)
       at cn.jzvd.Jzvd.backPress(Jzvd.java:234)
       at cn.jzvd.JzvdStd.clickBack(JzvdStd.java:416)
       at cn.jzvd.JzvdStd.onClick(JzvdStd.java:336)
       at com.xxx.video.JzPlayerView.onClick(JzPlayerView.java:55)
       at android.view.View.performClick(View.java:7288)
       at android.view.View.performClickInternal(View.java:7258)
       at android.view.View.access$4000(View.java:808)
       at android.view.View$PerformClick.run(View.java:28019)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

其实有看到注释说
`如果全屏或者返回全屏的视图有问题，复写这两个函数gotoScreenNormal(),根据自己布局的情况重新布局。`
但是不是很了解这里做的操作问题出在哪里，所以无从下手，请指点复写方法的思路或者这个问题的解决方案？

**Comment by xxxifan** [comment]
其实有搜到类似issues，但是很久了，似乎没人管，故重提一下。

**Comment by Liberations** [comment]
复现的频率如何

**Comment by Liberations** [comment]
查看 #151 看看是否混淆的问题

**Comment by Liberations** [comment]
参考最新混淆规则 看看问题是否解决

**Comment by xxxifan** [comment]
```
-keep public class cn.jzvd.JZMediaSystem {*; }
-keep public class * extends cn.jzvd.JZMediaInterface {*; }
```
确实没有把继承自Jzvd的类加进去，我试试，后续再反馈。

**Comment by waterpotter** [comment]
-keep public class cn.jzvd.JZMediaSystem {*; }
-keep public class * extends cn.jzvd.JZMediaInterface {*; }
解决了我的问题，可以加上试试
