### ISSUE TITLE
android.view.WindowManager$BadTokenException: at cn.jzvd.JzvdStd.showWifiDialog(JzvdStd.java:511)

### ISSUE THREAD

**Issue by qq610717306** [Jzvd/JiaoZiVideoPlayer#335]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by qq610717306** [comment]
Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@fc00738 is not valid; is your activity running? 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:788)
