### ISSUE TITLE
Caused by: android.view.WindowManager$BadTokenException

### ISSUE THREAD

**Issue by qq610717306** [Jzvd/JiaoZiVideoPlayer#336]
at cn.jzvd.JzvdStd.showWifiDialog(JzvdStd.java:511)
	at cn.jzvd.JzvdStd$2.onReceive(JzvdStd.java:99)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1222)

**Comment by Liberations** [comment]
怎么操作的？看这个样子是这个上下文有问题

**Comment by qq610717306** [comment]
统计回来的错误信息，本地没有复现过。出现概率比较低。
