### ISSUE TITLE
Android8.0适配-Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by tdxtxt** [Jzvd/JiaoZiVideoPlayer#342]
**什么jzvd版本
v7.6.0
**相关log是什么
```
java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.os.Parcel.readException(Parcel.java:1962)
        at android.os.Parcel.readException(Parcel.java:1900)
        at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5704)
        at android.app.Activity.setRequestedOrientation(Activity.java:6132)
        at cn.jzvd.JZUtils.setRequestedOrientation(JZUtils.java:78)
        at cn.jzvd.Jzvd.gotoFullscreen(Jzvd.java:1000)
        at cn.jzvd.Jzvd.clickFullscreen(Jzvd.java:362)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:350)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:328)
        at cn.jzvd.demo.CustomJzvd.JzvdStdRv.onClick(JzvdStdRv.java:42)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```
**demo是否有这个问题
demo会出现这个问题
**自己做了哪些修改

**如何操作复现
列表->列表详情页无缝切换演示->播放任意视频->再点击视频进入详情（此时会闪退）
将视频详情页配置的android:screenOrientation="portrait"去掉后，能进入详情，但点击视频右下角全屏播放也会闪退
**什么安卓版本，什么机型
荣耀8  android8.0

**Comment by Liberations** [comment]
暂不解决。。应该是8.0限定了透明activity的方向 你可以尝试用 fragment替代，或者去除详情页的主题TransparentWindow
https://blog.csdn.net/Jason_Julie/article/details/87860230
