### ISSUE TITLE
 java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by rongkai** [Jzvd/JiaoZiVideoPlayer#345]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5131)
        at android.view.ViewGroup.addView(ViewGroup.java:4960)
        at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1009)
        at cn.jzvd.Jzvd.backPress(Jzvd.java:235)
        at cn.jzvd.demo.Tab_1_Basic.CustomMediaActivity.onBackPressed(CustomMediaActivity.java:86)
        at android.app.Activity.onKeyUp(Activity.java:3654)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2825)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3971)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
demo中出现的问题复现步骤如下：
在播放界面的onPause中写入Jzvd.releaseAllVideos();

**Comment by rongkai** [comment]
然后全屏播放视频，然后再锁屏，再打开手机按手机的返回键，这个时候整个播放界面直接退出，再次进入播放界面播放视频，这个时候按返回建，bug复现
最新版v7.6.0还是有这样的问题

**Comment by Liberations** [comment]
看看最新的提交。这边如果希望onPause执行仍然能恢复播放releaseAllVideos在onDestroy调用比较合适。

**Comment by NingJinBo** [comment]
+1
