### ISSUE TITLE
 ijkPlayer内核，changeUrl的时候崩溃的问题

### ISSUE THREAD

**Issue by Juslt** [Jzvd/JiaoZiVideoPlayer#35]
**什么jzvd版本
7.0.5
**相关log是什么
2019-12-31 18:06:21.766 8330-8699/com.android.benlailife.activity E/CrashReport: java.lang.IllegalArgumentException: surfaceTexture must not be null
        at android.view.Surface.<init>(Surface.java:219)
        at com.android.benlai.view.video.JZMediaIjk.lambda$prepare$0$JZMediaIjk(JZMediaIjk.java:70)
        at com.android.benlai.view.video.-$$Lambda$JZMediaIjk$UI-nD8X_LbpC8ryEPMkSuh36Nqc.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
**demo是否有这个问题

**如何操作复现
播放过程中，调用changeUrl启动更换视频，应用崩溃
**什么安卓版本，什么机型
android 10 , oneplus7pro
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
changeUrl本质上和播放另一个视频是一样的，demo有这个问题吗

**Comment by dongfangmingjia** [comment]
请问这个问题怎么解决的

**Comment by hpp0hpp** [comment]
同样出现这个问题，不知道怎么回事。

**Comment by hpp0hpp** [comment]
2021-08-12 14:41:13.254 20391-20714/com.shenma.tvlauncher E/AndroidRuntime: FATAL EXCEPTION: JZVD
    Process: com.shenma.tvlauncher, PID: 20391
    java.lang.IllegalArgumentException: surfaceTexture must not be null
        at android.view.Surface.<init>(Surface.java:180)
        at com.shenma.tvlauncher.AGVideo.mediaplayer.JZMediaIjk.lambda$prepare$0$JZMediaIjk(JZMediaIjk.java:95)
        at com.shenma.tvlauncher.AGVideo.mediaplayer.-$$Lambda$JZMediaIjk$o0pk1RPVoO3MERO_oL9AZaVNEAs.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:789)
