### ISSUE TITLE
视频多次播放后崩溃退出

### ISSUE THREAD

**Issue by Beseting** [Jzvd/JiaoZiVideoPlayer#353]
**什么jzvd版本 7.6.0

**什么播放器内核 默认

**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
        at cn.jzvd.JZMediaSystem.start(JZMediaSystem.java:61)
        at cn.jzvd.Jzvd.onPrepared(Jzvd.java:568)
        at cn.jzvd.JZMediaSystem.lambda$onPrepared$6$JZMediaSystem(JZMediaSystem.java:139)
        at cn.jzvd.-$$Lambda$JZMediaSystem$WlYZGONHLrma_kOL0mIijCv1yRM.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6198)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by Liberations** [comment]
demo中是否复现？

**Comment by Beseting** [comment]
demo场景与应用场景有差异&nbsp; 应用场景为屏幕空闲时播放视频广告，一旦有数据刷新则关闭广告&nbsp; 经测试&nbsp; 多次播放关闭后（关闭调用的：JzvdStd.releaseAllVideos();）崩溃&nbsp;异常信息如issue所示




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jzvd/JZVideo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 晚上7:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jzvd/JZVideo] 视频多次播放后崩溃退出 (#353)





 
demo中是否复现？

**Comment by Liberations** [comment]
可否提供一个简易版的demo复现？
