### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.JZMediaInterface.getDuration()

### ISSUE THREAD

**Issue by jiaoyongzhi** [Jzvd/JiaoZiVideoPlayer#357]
**什么jzvd版本      7.6.0

**什么播放器内核  

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型    android9    vivo Z1
 
**截图或者视频说明情况java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.JZMediaInterface.getDuration()' on a null object reference
	at cn.jzvd.Jzvd.getDuration(Jzvd.java:910)
	at cn.jzvd.Jzvd.onProgressChanged(Jzvd.java:950)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:95)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1298)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1353)
	at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1418)
	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:891)
	at android.widget.AbsSeekBar.startDrag(AbsSeekBar.java:848)
	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:805)
	at android.view.View.dispatchTouchEvent(View.java:12609)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3071)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1009)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1932)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3508)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:957)
	at android.view.View.dispatchPointerEvent(View.java:12864)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5304)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5073)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4546)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4616)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4574)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4729)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4582)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4786)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4546)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4616)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4574)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4582)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4546)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7305)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7274)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7229)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7417)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:196)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7388)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7440)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
	at android.view.Choreographer.doCallbacks(Choreographer.java:875)
	at android.view.Choreographer.doFrame(Choreographer.java:801)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1049)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7053)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by Liberations** [comment]
做了什么操作 demo中是否复现？cn.jzvd.JZMediaInterface.getDuration()目前的确没有做判空处理

**Comment by Liberations** [comment]
#320

**Comment by yilylong** [comment]
public void setSpeed(float speed) {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
            PlaybackParams pp = mediaPlayer.getPlaybackParams();
            pp.setSpeed(speed);
            mediaPlayer.setPlaybackParams(pp);
        }
    }

这里也没判空mediaPlayer.getPlaybackParams()

**Comment by tusantrey2** [comment]
yeah when i see logcat same error with you `java.lang.NullPointerException`
