### ISSUE TITLE
正在播放视频，断开网络，提示正在使用移动网络弹窗，点击  停止播放  按钮闪退，pad运行。

### ISSUE THREAD

**Issue by 284361303** [Jzvd/JiaoZiVideoPlayer#358]
**需求描述

**其他app是否实现

**截图或者小视频说明
android.content.res.Resources$NotFoundException: Resource ID #0x7f0b0020
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3898)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6069)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5959)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0b0020
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:392)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2398)
        at android.content.res.Resources.getLayout(Resources.java:1292)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)

**Comment by Liberations** [comment]
demo中是否复现 Resources$NotFoundException: Resource ID #0x7f0b0020 这个ID找不到。
