### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.JZMediaInterface.getDuration()' on a null object reference

### ISSUE THREAD

**Issue by jiaoyongzhi** [Jzvd/JiaoZiVideoPlayer#360]
**什么jzvd版本
7.6.0
**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型
华为JKM-AL00 android9
**截图或者视频说明情况
java.lang.NullPointerException: Attempt to invoke virtual method 'long cn.jzvd.JZMediaInterface.getDuration()' on a null object reference
	at cn.jzvd.Jzvd.getDuration(Jzvd.java:910)
	at cn.jzvd.Jzvd.onProgressChanged(Jzvd.java:950)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:97)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1368)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1428)
	at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1499)
	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:899)
	at android.widget.AbsSeekBar.startDrag(AbsSeekBar.java:854)
	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:811)
	at android.view.View.dispatchTouchEvent(View.java:12628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3041)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2728)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:565)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1929)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3594)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:514)
	at android.view.View.dispatchPointerEvent(View.java:12873)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5771)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5535)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5157)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5214)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5036)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5002)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5010)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4983)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7803)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7768)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7726)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8007)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:202)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:191)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7917)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8061)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:893)
	at android.view.Choreographer.doFrame(Choreographer.java:806)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:907)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Back traces ends.

**Comment by Liberations** [comment]
getDuration需要在prepared之后获取
