### ISSUE TITLE
自定义view集成JzvdStd，点击全屏后点返回键或退出全屏键，应用void android.view.View.unFocus闪退

### ISSUE THREAD

**Issue by Sirliangs** [Jzvd/JiaoZiVideoPlayer#381]
**什么jzvd版本
7.7.0
**什么播放器内核
mediaplayer
**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5615)
        at android.view.ViewGroup.removeViewAt(ViewGroup.java:5578)
        at cn.jzvd.Jzvd.gotoNormalScreen(Jzvd.java:1011)
        at cn.jzvd.Jzvd.backPress(Jzvd.java:236)
        at com.geniuel.mall.ui.activity.TestActivity.onBackPressed(TestActivity.kt:26)
        at android.app.Activity.onKeyUp(Activity.java:3885)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2880)
        at android.app.Activity.dispatchKeyEvent(Activity.java:4191)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:403)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6204)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6053)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5525)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5582)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5700)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5556)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5757)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5582)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5556)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5529)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5582)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5733)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5906)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3210)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2752)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2743)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3187)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:8057)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
**demo是否有这个问题

**自己做了哪些修改
自定义view集成
**如何操作复现
点击全屏后点返回键或退出全屏键
**什么安卓版本，什么机型
android11 小米k40
**截图或者视频说明情况

**Comment by Sirliangs** [comment]
应用没有开启混淆，对应的混淆文件已加入。在布局里使用JzvdStd功能正常，自定义view集成后会出现以上问题

**Comment by Sirliangs** [comment]
![image](https://user-images.githubusercontent.com/20217057/128111348-347feb94-9b9a-4413-b277-4fe8220ed7e0.png)

**Comment by Akames** [comment]
这个问题我也遇到了

**Comment by Sirliangs** [comment]
![image](https://user-images.githubusercontent.com/20217057/128445219-882fbc76-7845-453a-ba55-9e033d007a29.png)
问题描述更新下，用JAVA方式继承开启或关闭混淆，以上问题不会发生了，用kt方式继承会有以上问题。

**Comment by lipangit** [comment]
所有的kt都无法混淆  还是jzvd的kt无法混淆

**Comment by Sirliangs** [comment]
用kt方式继承使用，不开启混淆也会出现unFocus。用java类继承使用，混淆开不开，都可以正常使用（开启状态下，已在混淆文件内加入作者所写的混淆内容）。

**Comment by Liberations** [comment]
请看demo中的混淆规则 #327

**Comment by zwping** [comment]
```
-keep class * extends cn.jzvd.JzvdStd { *; }
```
