### ISSUE TITLE
播放部分视频的时候，在全屏模式下滑动右侧声音，会报空指指针

### ISSUE THREAD

**Issue by loaderman** [Jzvd/JiaoZiVideoPlayer#386]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioManager.getStreamVolume(int)' on a null object reference
        at cn.jzvd.Jzvd.touchActionMove(Jzvd.java:471)
        at cn.jzvd.Jzvd.onTouch(Jzvd.java:404)
        at cn.jzvd.JzvdStd.onTouch(JzvdStd.java:323)

测试视频地址：http://videos.jzvd.org/v/ldj/01-ldj.mp4

**Comment by xaEHu** [comment]
看这个：https://github.com/Jzvd/JZVideo/issues/401
