### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by HuYueling** [Jzvd/JiaoZiVideoPlayer#389]
**什么jzvd版本
7.7.0
**什么播放器内核
默认
**相关log是什么
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9286)
	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4944)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:965)
	at android.view.View.setFlags(View.java:16323)
	at android.view.View.setVisibility(View.java:11808)
	at android.widget.ImageView.setVisibility(ImageView.java:1700)
	at cn.jzvd.JzvdStd.setAllControlsVisiblity(JzvdStd.java:771)
	at cn.jzvd.JzvdStd.changeUiToNormal(JzvdStd.java:632)
	at cn.jzvd.JzvdStd.onStateNormal(JzvdStd.java:216)
	at cn.jzvd.Jzvd.reset(Jzvd.java:716)
	at cn.jzvd.JzvdStd.reset(JzvdStd.java:933)
	at cn.jzvd.Jzvd.releaseAllVideos(Jzvd.java:227)
	at cn.jzvd.Jzvd$1.onAudioFocusChange(Jzvd.java:77)
	at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2995)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:239)
	at com.tencent.rtmp.sharp.jni.TraeAudioManager$TraeAudioManagerLooper.run(TraeAudioManager.java:2058)
**demo是否有这个问题
未复现
**自己做了哪些修改
我使用的的viewpager2里面嵌入播放器，然后每次来到页面请求到数据后自动播放
**如何操作复现

**什么安卓版本，什么机型
iQOO Neo3 Android11
**截图或者视频说明情况

**Comment by HuYueling** [comment]
我上一个页面有使用到系统的videoview，请问一下这个会影响吗

**Comment by Liberations** [comment]
保证主线程

**Comment by LucasXu01** [comment]
遇到一样的问题，没有切换子线程啊，但是根据日志播放器又是在子线程更新UI的，请问怎么解决的？

**Comment by HysonHou** [comment]
我这里也出现了,看了源码怎么不用handler更新UI

**Comment by LucasXu01** [comment]
解决了，源码确实可以再修改一下。大家再对应报错的UI更新的代码块上，包裹一层，跑在主线程就好了。比如继承的JzvdStd，重写他的changeUI方法，直接复用源码，但是runonUiThread就ok了

**Comment by HysonHou** [comment]
> 解决了，源码确实可以再修改一下。大家再对应报错的UI更新的代码块上，包裹一层，跑在主线程就好了。比如继承的JzvdStd，重写他的changeUI方法，直接复用源码，但是runonUiThread就ok了

changeUiToNormal是这个方法吗 ，线上就没出现这样的奔溃了？

**Comment by HysonHou** [comment]
> > 解决了，源码确实可以再修改一下。大家再对应报错的UI更新的代码块上，包裹一层，跑在主线程就好了。比如继承的JzvdStd，重写他的changeUI方法，直接复用源码，但是runonUiThread就ok了
> 
> changeUiToNormal是这个方法吗 ，线上就没出现这样的奔溃了？

@Liberations 请问 你有解决办法吗
