### ISSUE TITLE
7.7.0问题

### ISSUE THREAD

**Issue by q1170541047** [Jzvd/JiaoZiVideoPlayer#420]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioManager.getStreamVolume(int)' on a null object reference
       at cn.jzvd.Jzvd.touchActionMove(Jzvd.java:471)
       at cn.jzvd.Jzvd.onTouch(Jzvd.java:404)
       at cn.jzvd.JzvdStd.onTouch(JzvdStd.java:323)
       at android.view.View.dispatchTouchEvent(View.java:14364)
7.6升级7.7才会出现这个问题而且报错率极高

**Comment by lipangit** [comment]
收到 感谢反馈。看样是声音调节，空指针



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月19日(周日) 中午1:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] 7.7.0问题 (Issue #420)




 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.AudioManager.getStreamVolume(int)' on a null object reference
 at cn.jzvd.Jzvd.touchActionMove(Jzvd.java:471)
 at cn.jzvd.Jzvd.onTouch(Jzvd.java:404)
 at cn.jzvd.JzvdStd.onTouch(JzvdStd.java:323)
 at android.view.View.dispatchTouchEvent(View.java:14364)
 7.6升级7.7才会出现这个问题而且报错率极高
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zaiyubuzai** [comment]
我也有这个问题

**Comment by wanghuabing** [comment]
这个问题有解决计划吗？同样遇到这个问题
