### ISSUE TITLE
HarmonyOS 3.0 (Mate 50 Pro） library "libijkffmpeg.so" not found

### ISSUE THREAD

**Issue by tudoutiao** [Jzvd/JiaoZiVideoPlayer#482]
HarmonyOS 3.0 (Mate 50 Pro）环境下运行崩溃，提示如下

> 03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: java.lang.UnsatisfiedLinkError: dlopen failed: library "libijkffmpeg.so" not found
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at java.lang.Runtime.loadLibrary0(Runtime.java:998)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at java.lang.System.loadLibrary(System.java:1657)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:179)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:190)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:231)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:227)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:218)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at cn.jzvd.demo.CustomMedia.JZMediaIjk.lambda$prepare$0$cn-jzvd-demo-CustomMedia-JZMediaIjk(JZMediaIjk.java:46)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at cn.jzvd.demo.CustomMedia.JZMediaIjk$$ExternalSyntheticLambda3.run(Unknown Source:2)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at android.os.Handler.handleCallback(Handler.java:966)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at android.os.Handler.dispatchMessage(Handler.java:110)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at android.os.Looper.loopOnce(Looper.java:205)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at android.os.Looper.loop(Looper.java:293)
03-30 20:03:56.723 10871-11192/cn.jzvd.demo E AndroidRuntime/: at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by tudoutiao** [comment]
> ```
 # required, enough for most devices.
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'

    # Other ABIs: optional
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.8'

    # ExoPlayer as IMediaPlayer: optional, experimental
    compile 'tv.danmaku.ijk.media:ijkplayer-exo:0.8.8'
```
