### ISSUE TITLE
使用系统内核出错。

### ISSUE THREAD

**Issue by Anzhilia** [Jzvd/JiaoZiVideoPlayer#486]
**什么jzvd版本' cn.jzvd:jiaozivideoplayer:7.7.0'

**什么播放器内核  JZMediaSystemAssertFolder.class

**相关log是什么

java.lang.IllegalArgumentException: Receiver not registered: cn.jzvd.JzvdStd$2@20957a8
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1271)
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1504)
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at cn.jzvd.JzvdStd.unregisterWifiListener(JzvdStd.java:964)
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at cn.jzvd.JzvdStd.reset(JzvdStd.java:935)
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at cn.jzvd.Jzvd.setMediaInterface(Jzvd.java:341)
2023-05-05 17:20:41.050  3398-3398  System.err              com.anni.tv                          W  	at com.example.tbs.VideoActivity.onCreate(VideoActivity.java:26)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.Activity.performCreate(Activity.java:7144)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.Activity.performCreate(Activity.java:7135)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2934)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3089)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1819)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.os.Looper.loop(Looper.java:193)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at android.app.ActivityThread.main(ActivityThread.java:6737)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at java.lang.reflect.Method.invoke(Native Method)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2023-05-05 17:20:41.051  3398-3398  System.err              com.anni.tv                          W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
2023-05-05 17:20:41.051  3398-3398  JZVD                    com.anni.tv                          D  startVideo [4106126] 
2023-05-05 17:20:41.051  3398-3398  JZVD                    com.anni.tv                          D  addTextureView [4106126] 
2023-05-05 17:20:41.052  3398-3398  JZVD                    com.anni.tv                          I  onStatePreparing  [4106126] 
2023-05-05 17:20:41.086  3398-3398  JZResizeTextureView     com.anni.tv                          I  onMeasure  [73272300] 
2023-05-05 17:20:41.093  3398-3398  chatty                  com.anni.tv                          I  uid=10050(com.anni.tv) identical 2 lines
2023-05-05 17:20:41.094  3398-3398  JZResizeTextureView     com.anni.tv                          I  onMeasure  [73272300] 
2023-05-05 17:20:41.104  3398-3440  EGL_adreno              com.anni.tv                          E  tid 3440: eglSurfaceAttrib(1338): error 0x3009 (EGL_BAD_MATCH)
2023-05-05 17:20:41.104  3398-3440  OpenGLRenderer          com.anni.tv                          W  Failed to set EGL_SWAP_BEHAVIOR on surface 0x7fff5a979880, error=EGL_BAD_MATCH
2023-05-05 17:20:41.115  3398-3398  GD                      com.anni.tv                          I  ======= onSurfaceTextureAvailable =======
2023-05-05 17:20:41.120  3398-3440  EGL_adreno              com.anni.tv                          D  eglMakeCurrent: 0x7fff6a240340: ver 3 1 (tinfo 0x7fff72686fa0)
2023-05-05 17:20:41.121  3398-3585  MediaPlayer             com.anni.tv                          W  Use of stream types is deprecated for operations other than volume control
2023-05-05 17:20:41.121  3398-3585  MediaPlayer             com.anni.tv                          W  See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2023-05-05 17:20:41.125  3398-3585  MediaPlayer             com.anni.tv                          W  setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
2023-05-05 17:20:41.126  3398-3585  System.err              com.anni.tv                          W  java.io.FileNotFoundException: https://sf9-dycdn-tos.pstatp.com/obj/tos-cn-i-8gu37r9deh/0888c7da2e2a4ac98f696ea0abd98959?filename=1.mp4
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at android.content.res.AssetManager.openFd(AssetManager.java:768)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at com.example.tbs.JZMediaSystemAssertFolder.lambda$prepare$0$com-example-tbs-JZMediaSystemAssertFolder(JZMediaSystemAssertFolder.java:59)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at com.example.tbs.JZMediaSystemAssertFolder$$ExternalSyntheticLambda1.run(Unknown Source:2)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at android.os.Handler.handleCallback(Handler.java:873)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at android.os.Looper.loop(Looper.java:193)
2023-05-05 17:20:41.128  3398-3585  System.err              com.anni.tv                          W  	at android.os.HandlerThread.run(HandlerThread.java:65)

**demo是否有这个问题

**自己做了哪些修改  自己继承了一个 JzvdStd

package com.example.tbs;

import androidx.appcompat.app.AppCompatActivity;

import cn.jzvd.Jzvd;
import cn.jzvd.JzvdStd;

import android.content.Intent;
import android.os.Bundle;

import com.anni.tv.R;

public class VideoActivity extends AppCompatActivity {
  private AVideo jzvdStd;
  //private JzvdStd jzvdStd;
  String url;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video);
        Intent intent = getIntent();
        url = intent.getStringExtra("url");
        jzvdStd = findViewById(R.id.jz_video);
        jzvdStd.setUp(url, "视频Video");
        jzvdStd.setMediaInterface(JZMediaSystemAssertFolder.class);
        jzvdStd.startVideoAfterPreloading(); //如果预加载完会开始播放，如果未加载则开始加载
    }
    @Override
    public void onBackPressed() {
        if (AVideo.backPress()) {
           return;
        }
        super.onBackPressed();
    }
    @Override
    protected void onPause() {
        super.onPause();
        AVideo.releaseAllVideos();
    }

}

**如何操作复现

**什么安卓版本，什么机型

雷电模拟器 

**截图或者视频说明情况

**Comment by rockerkekex** [comment]
请问解决了吗？ 碰到了同样的问题
