### ISSUE TITLE
ActivityListViewMultiHolder页面Bug

### ISSUE THREAD

**Issue by cs1439071609** [Jzvd/JiaoZiVideoPlayer#53]
**什么jzvd版本
7.2.0
**相关log是什么
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at cn.jzvd.Jzvd.gotoScreenFullscreen(Jzvd.java:752)
        at cn.jzvd.Jzvd.onClick(Jzvd.java:210)
        at cn.jzvd.JzvdStd.onClick(JzvdStd.java:250)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
**demo是否有这个问题

**如何操作复现
ActivityListViewMultiHolder页面点击退出全屏按钮崩溃
**什么安卓版本，什么机型

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
兄弟 这个页面确实有问题，感谢你的反馈  给你1000jzt，加我微信。

**Comment by lipangit** [comment]
fix on 4cecce145701ba1209081d29e6129823309b344a

**Comment by lipangit** [comment]
2967574c5aa2d0806c702b5ec9f30b634852cd2f
