### ISSUE TITLE
startFullscreenDirectly 直接全屏播放，视频播放结束后，会出现空指针报错

### ISSUE THREAD

**Issue by Tracycuizh** [Jzvd/JiaoZiVideoPlayer#54]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window android.app.Activity.getWindow()' on a null object reference
        at cn.jzvd.Jzvd.gotoScreenNormal(Jzvd.java:765)
        at cn.jzvd.Jzvd.onAutoCompletion(Jzvd.java:451)
        at cn.jzvd.JzvdStd.onAutoCompletion(JzvdStd.java:811)
        at cn.jzvd.JZMediaSystem.lambda$onCompletion$7$JZMediaSystem(JZMediaSystem.java:144)
        at cn.jzvd.JZMediaSystem$$Lambda$7.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

**Comment by lipangit** [comment]
哪个jzvd版本，demo有这问题吗，实现步骤怎么样

**Comment by Tracycuizh** [comment]
7.2.0版本，步骤就是直接调用Jzvd.startFullscreenDirectly(Context context, Class _class, String url, String title)方法；使用7.1.0版本则运行正常没报错

**Comment by lipangit** [comment]
感谢你的反馈，正在修复，加我微信，给你1000jzt&nbsp;https://github.com/Jzvd/JZT




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tracycuizh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月25日(星期二) 下午5:35
收件人:&nbsp;"Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送:&nbsp;"李盼"<1066666651@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Jzvd/JiaoZiVideoPlayer] startFullscreenDirectly 直接全屏播放，视频播放结束后，会出现空指针报错 (#54)




7.2.0版本，步骤就是直接调用Jzvd.startFullscreenDirectly(Context context, Class _class, String url, String title)方法；使用7.1.0版本则运行正常没报错

**Comment by lipangit** [comment]
已经修复
